### ISSUE TITLE
BUG - JWT Refresh token bug

### ISSUE THREAD

**Issue by LukeDerpwalka** [JonahKoellner/transendence#1]
Der token sollte sich nach einer weile refreshen. das ist mies buggy und irgendwie sagt das backend token fehlt und spammt das zu. nix wird gehandled. 

Erwartet: refresh die tokens

was is: angular spammt das backend zu und failt

wie?

registriere dich, logge ein, mach otp, warte auf der homeseite angemeldet

**Comment by JonahKoellner** [comment]
The issue was that the url was set to 127.0.0.1 instead of localhost, like with all the others. Push should have fixed that.
