### ISSUE TITLE
BUG - Live Chat und Real Time Notifications

### ISSUE THREAD

**Issue by LukeDerpwalka** [JonahKoellner/transendence#2]
Hab das irgendwie schon vorbereitet/versucht. aber geht doch noch ned ganz

is ned live aber mit refresh geht

live notifications und chat fixen pls

**Comment by JonahKoellner** [comment]
Sockets had an error /ws/notification url was not registered. As well as the component. Now the websockets work and the notification does as well. The chat still has an issue, since there is some live event but without the message being printed.

**Comment by JonahKoellner** [comment]
The bug was in the chat.service.ts receiveMessages(). The notification object wasnt handled correctly. Fixed it and tested it. Notification, live message and room name is now working.
