### ISSUE TITLE
weird local tournament bug

### ISSUE THREAD

**Issue by nburchha** [JonahKoellner/transendence#30]
tournament pve tie-resolving in the beginning of each game

happens in round robin and in single elimination.

seems like it treats the 0:0 score as a tie and tries to resolve that? idk

https://github.com/user-attachments/assets/350fd01d-f4ef-4f13-beb4-b8bccb5f0568

<img width="1274" alt="Screenshot 2024-12-13 at 14 34 17" src="https://github.com/user-attachments/assets/56463858-ada5-4143-85f3-24f23eedea19" />

**Comment by LukeDerpwalka** [comment]
ah lmao game timer is 1 second right now instead of 90 since i cant be fucked to play for so long
