### ISSUE TITLE
clear all user data on logout lol

### ISSUE THREAD

**Issue by LukeDerpwalka** [JonahKoellner/transendence#9]
i look at you messages

**Comment by bloodbine** [comment]
Added a clear all button to notifications. Imo it doesn't make sense to clear notifications on logout, in case you have unread notifications on next login.

**Comment by JonahKoellner** [comment]
If you logout then someone else shouldnt be able to read your messages / notifications.

**Comment by bloodbine** [comment]
Tested, messages and notifications are fetched each time after login and if there was any previous data, it gets overridden before the new user could access it.

**Comment by LukeDerpwalka** [comment]
did we already review?
